name: engage
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.7
  datetime_picker_formfield: ^1.0.0
  firebase_auth: ^0.16.1
  freezed_annotation: ^0.11.0
  google_sign_in: ^4.5.1
  json_annotation: ^3.0.1
  provider: ^4.1.3
  websafe_svg: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  freezed: ^0.11.2
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Bios
      fonts:
        - asset: assets/fonts/Bios_Bold.otf
        - asset: assets/fonts/Bios_Regular.otf
    - family: Avalon
      fonts:
        - asset: assets/fonts/Avalon.otf
